name: Static Analysis

on: ['push', 'pull_request']

jobs:
  pint:
    runs-on: ubuntu-latest

    name: Pint

    steps:

      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: zip
          coverage: none

      - name: Install PHP dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: highest
          composer-options: "--prefer-dist"

      - name: Run Pint
        run: vendor/bin/pint --test --ansi

  phpstan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dependency-version: [prefer-lowest, prefer-stable]

    name: PHPStan (${{ matrix.dependency-version }})

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        coverage: none

    - name: Install PHP dependencies
      uses: ramsey/composer-install@v3
      with:
        dependency-versions: highest
        composer-options: "--prefer-dist"

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --no-progress --ansi
